# rutas.yml
---
ruta_raíz:
  path:     /
  controller: 'funcionHomePage'
  methods:   [ GET ]

ruta_user_list:
  path:     /user/list
  controller: 'funcionListadoUsers'
  methods:
    - GET

ruta_user_nuevo:
  path:       /user/new
  controller: 'funcionNuevoUser'
  methods:   [ GET, POST ]